#???????
spring:
  profiles:
    active: dev
---
#??
spring:
  profiles: dev
server:
  port: 8080

---
#??
spring:
  profiles: pro
server:
  port: 8081

---
#??
spring:
  profiles: test
server:
  port: 8082
